db:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: "insecurepassword"
consul:
  image: progrium/consul
  net: host
  command: "-server -bootstrap -ui-dir /ui"
elk:
  image: spantree/elk
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5000:5000"
    - "3333:3333"