#cloud-config
write_files:
  - path: /etc/default/barker-app
    permissions: 0644
    owner: root
    content: |
      export CONSUL_URL=http://10.0.0.249:8500
      export HOME=/home/ubuntu
      export RAILS_ENV=production
runcmd:
 - service barker-app restart